# Generated by Django 4.0.6 on 2024-03-16 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tipos_documento_identidad',
            name='id',
            field=models.PositiveSmallIntegerField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
