# Generated by Django 4.0.6 on 2024-03-16 20:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_alter_tipos_documento_identidad_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='usuarios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('correo_electronico', models.EmailField(max_length=250, unique=True, verbose_name='Correo electrónico')),
                ('nombre_usuario', models.CharField(max_length=350, verbose_name='Nombre de usuario')),
                ('nclave', models.CharField(max_length=350, verbose_name='Clave')),
                ('documento_identidad', models.CharField(max_length=350, verbose_name='Documento de identidad')),
                ('nombres', models.CharField(max_length=350, verbose_name='Nombres')),
                ('apellidos', models.CharField(max_length=350, verbose_name='Apellidos')),
                ('cargo', models.CharField(choices=[('DA', 'DIRECTOR DE ARQUITECTURA'), ('AA', 'AUXILIAR DE ARQUITECTURA'), ('DC', 'DIRECTOR DE CONTABILIDAD'), ('AC', 'AUXILIAR DE CONTABILIDAD')], max_length=3, null=True, verbose_name='Cargo')),
                ('dependencia', models.CharField(choices=[('ARQ', 'ARQUITECTURA'), ('CONT', 'CONTABILIDAD')], max_length=10, null=True, verbose_name='Dependencia')),
                ('fecha_registro', models.DateField(auto_now_add=True, verbose_name='Fecha de registro')),
                ('fecha_ultimo_ingreso', models.DateField(auto_now_add=True, verbose_name='Fecha de último ingreso')),
                ('tipo_documento_identidad', models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='mainapp.tipos_documento_identidad', verbose_name='Tipo de documento de identidad')),
            ],
        ),
    ]
