# Generated by Django 4.0.6 on 2024-03-16 21:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0003_usuarios'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tipos_documento_identidad',
            options={'verbose_name': 'Tipo de documento de identidad', 'verbose_name_plural': 'Tipos de documento de identidad'},
        ),
        migrations.AlterModelOptions(
            name='usuarios',
            options={'verbose_name': 'Usuario', 'verbose_name_plural': 'Usuarios'},
        ),
    ]
