# Generated by Django 4.0.6 on 2024-03-16 21:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0004_alter_tipos_documento_identidad_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usuarios',
            old_name='nclave',
            new_name='clave',
        ),
    ]
