# Generated by Django 4.0.6 on 2024-03-16 21:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0005_rename_nclave_usuarios_clave'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuarios',
            name='tipo_documento_identidad',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='mainapp.tipos_documento_identidad', verbose_name='Tipo de documento de identidad'),
        ),
    ]
