# Generated by Django 4.0.6 on 2024-03-17 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0006_alter_usuarios_tipo_documento_identidad'),
    ]

    operations = [
        migrations.CreateModel(
            name='establecimientos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=250, verbose_name='Código')),
                ('nombre', models.CharField(max_length=350, verbose_name='Nombre')),
                ('jefe_zona', models.CharField(choices=[('ALE_SAU', 'ALEX SAUVET'), ('MER_CHA', 'MERLINA CHÁVEZ'), ('JHO_CAS', 'JHON CASTILLO')], max_length=10, null=True, verbose_name='Jefe de zona')),
                ('ciudad', models.CharField(choices=[('MED', 'MEDELLÍN'), ('BEL', 'BELLO'), ('SAN_MAR', 'SANTA MARTA'), ('CAL', 'CALI'), ('BOG', 'BOGOTÁ'), ('IPI', 'IPIALES')], max_length=10, null=True, verbose_name='Ciudad')),
                ('telefono', models.BigIntegerField(verbose_name='Teléfono')),
                ('direccion', models.CharField(max_length=500, verbose_name='Dirección')),
            ],
            options={
                'verbose_name': 'Establecimiento',
                'verbose_name_plural': 'Establecimientos',
            },
        ),
    ]
