# Generated by Django 4.0.6 on 2024-03-17 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0007_establecimientos'),
    ]

    operations = [
        migrations.CreateModel(
            name='objetos_gasto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=350, verbose_name='Nombre')),
                ('descripcion', models.CharField(max_length=500, verbose_name='Descripción')),
            ],
            options={
                'verbose_name': 'Objeto de gasto',
                'verbose_name_plural': 'Objetos de gasto',
            },
        ),
    ]
