# Generated by Django 4.0.6 on 2024-03-18 03:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0008_objetos_gasto'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuarios',
            name='fecha_ultimo_ingreso',
        ),
        migrations.CreateModel(
            name='presupuestos_gastos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anio', models.BigIntegerField(verbose_name='Año')),
                ('mes', models.SmallIntegerField(verbose_name='Mes')),
                ('presupuesto', models.DecimalField(decimal_places=30, max_digits=60, verbose_name='Presupuesto')),
                ('gasto', models.DecimalField(decimal_places=30, max_digits=60, verbose_name='Gasto')),
                ('fecha_creacion', models.DateField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('establecimiento', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='mainapp.establecimientos', verbose_name='Establecimiento')),
                ('objeto_gasto', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='mainapp.objetos_gasto', verbose_name='Objeto de gasto')),
                ('usuario_creacion', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='mainapp.usuarios', verbose_name='Usuario de creación')),
            ],
            options={
                'verbose_name': 'Objeto de gasto',
                'verbose_name_plural': 'Objetos de gasto',
            },
        ),
    ]
