# Generated by Django 4.0.6 on 2024-03-26 15:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0009_remove_usuarios_fecha_ultimo_ingreso_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='presupuestos_gastos',
            name='usuario_creacion',
        ),
    ]
